var data1 = {
  id: 1,
  clustername: "Cluster1",
  background: "red",
  users: [
    {"icon": 1},
    {"icon": 1},
    {"icon": 1},
    {"icon": 1},
    {"icon": 1},
    {"icon": 1},
    {"icon": 1},
    {"icon": 2},
    {"icon": 2},
    {"icon": 2},
    {"icon": 2},
    {"icon": 2},
    {"icon": 2},
    {"icon": 2},
    {"icon": 2},
    {"icon": 2},
    {"icon": 2},
    {"icon": 2},
    {"icon": 0},
    {"icon": 0},
    {"icon": 0},
    {"icon": 0},
    {"icon": 0},
    {"icon": 0},
    {"icon": 0},
    {"icon": 0},
    {"icon": 0},
    {"icon": 0},
    {"icon": 0},
    {"icon": 0}, 
  ]
  }
 